name: GamemodeUI
main: GamemodeUI\LaithYT\Main
version: 1.0
api: [3.0.0]
author: David
description: Easily Chang Gamemode
website: https://github.com/davidlouis101

commands: 
 gm:
    description: "GamemodeUI Command"
    permission: "gm.cmd"
permissions:
 gm.cmd:
    description: "GamemodeUI Permission"
    defualt: op
